### 유저 회원가입
POST localhost:8080/auth/signup
content-type: application/json

{
  "name": "윤경모",
  "email": "userf123@naver.com",
  "password": "asdasdjkDF23",
  "role": "STUDENT"
}

### 튜터 회원가입


### 관리자 로그인

POST localhost:8080/api/auth/login
content-type: application/json

{
  "email": "admin123@naver.com",
  "password": "asdasdjkDF!@#"
}

> {% client.global.set("accessToken", response.body.data.accessToken) %}




