### 게시글 등록
POST localhost:8080/boards
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "title": "공개글 테스트",
  "content": "이건 일반 공개 게시글입니다.",
  "tag": "정보",
  "secret": false,
  "userId": 1
}

### 게시글 전체 조회 (학생)
GET localhost:8080/boards
Authorization: Bearer {{studentAccessToken}}

### 게시글 수정
PUT localhost:8080/boards/1
Authorization: Bearer {{studentAccessToken}}
Content-Type: application/json

{
  "title": "공개글 수정됨",
  "content": "내용이 수정되었습니다.",
  "tag": "후기",
  "secret": false,
  "userId": 1
}

### 게시글 추천
PUT localhost:8080/boards/1/recommend
Authorization: Bearer {{studentAccessToken}}

### 게시글 추천 취소
DELETE localhost:8080/boards/1/recommend
Authorization: Bearer {{studentAccessToken}}

### 인기 게시글 조회
GET localhost:8080/boards/popular
Authorization: Bearer {{studentAccessToken}}

### 스크랩 추가
POST localhost:8080/boards/1/scrap
Authorization: Bearer {{studentAccessToken}}

### 스크랩 여부 확인
GET localhost:8080/boards/1/scrap
Authorization: Bearer {{studentAccessToken}}

### 스크랩 목록 조회
GET localhost:8080/boards/scraps
Authorization: Bearer {{studentAccessToken}}

### 스크랩 취소
DELETE localhost:8080/boards/1/scrap
Authorization: Bearer {{studentAccessToken}}