### 학생 회원가입
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "윤경모",
  "email": "user1234@naver.com",
  "password": "asdasdjkDF23",
  "role": "STUDENT"
}

### 학생 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user1234@naver.com",
  "password": "asdasdjkDF23"
}

> {%
    client.global.set("studentAccessToken", response.body.data.accessToken)
    client.global.set("studentRefreshToken", response.body.data.refreshToken)
%}

### 튜터 회원가입
POST localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "윤경모",
  "email": "tutor123@naver.com",
  "password": "asdasdjkDF23",
  "role": "TUTOR"
}

### 튜터 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "tutor123@naver.com",
  "password": "asdasdjkDF23"
}

> {%
    client.global.set("tutorAccessToken", response.body.data.accessToken)
%}

### 문서 등록
POST localhost:8080/documents
Authorization: Bearer {{studentAccessToken}}
Content-Type: multipart/form-data; boundary=my-upload-boundary

--my-upload-boundary
Content-Disposition: form-data; name="file"; filename="test-image-20.png"
Content-Type: application/png

< ../src/main/resources/test-image-20.png
--my-upload-boundary--

### 문서 목록 조회
GET localhost:8080/documents
Authorization: Bearer {{studentAccessToken}}

### 문서 단건 조회
GET localhost:8080/documents/1
Authorization: Bearer {{studentAccessToken}}

### 문서 단건 삭제
DELETE localhost:8080/documents/1
Authorization: Bearer {{studentAccessToken}}